// exception handling:--exception handling is a process to handle the errors.
// try block:--The try block in C# is used to place the code that may throw exception. 
// catch:-- the catch block is used to handled the exception.

  
// finally:-- C# finally block is used to execute important code which is to be executed whether exception is handled or not. It must be preceded by catch or try block.

// Common Exception class:-
// All the exception classes in C# are derived from System.Exception class. Let's see the list of C# common exception classes.
// 1.System.DivideByZeroException:-handles the error generated by dividing a number with zero.
// 2.System.NullReferenceException :- handles the error generated by referencing the null object.
// 3.System.IO.IOException:- handles the Input Output errors.

  
using System;  
public class ExExample  
{  
    public static void Main(string[] args)  
    {  
        try  
        {  
            int a = 10;  
            int b = 0;  
            int x = a / b;  
        }  
        catch (Exception e) { Console.WriteLine(e); }  
  
        Console.WriteLine("Rest of the code");  
    }  
}  


  
